config/routes.rb
 Doit::Application.routes.draw do


devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

resources :todos

   get 'about' => 'welcome#about'

   root to: 'welcome#index'

 match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :todo
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          name: auth.extra.raw_info.name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :ensure_signup_complete, only: [:new, :create, :update, :destroy]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Pundit
  helper_method :current_user
  rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end

    def index
    end

    def about
    end

  

   def ensure_signup_complete
    # Ensure we don't go into an infinite loop
    return if action_name == 'finish_signup'

    # Redirect to the 'finish_signup' page if the user
    # email hasn't been verified yet
    if current_user && !current_user.email_verified?
      redirect_to finish_signup_path(current_user)
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %Q{
      def #{provider}
        @user = User.find_for_oauth(env["omniauth.auth"], current_user)

        if @user.persisted?
          sign_in_and_redirect @user, event: :authentication
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url
        end
      end
    }
  end

  [:twitter, :facebook].each do |provider|
    provides_callback_for provider
  end

  def after_sign_in_path_for(resource)
    if resource.email_verified?
      super resource
    else
      finish_signup_path(resource)
    end
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
     @todo = Todo.new(params.require(:todo).permit(:title, :body))
     if @todo.save
       flash[:notice] = "Todo was saved."
       redirect_to @todo
     else
       flash[:error] = "There was an error saving the todo. Please try again."
       render :new
     end
   end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
     @todo = Todo.find(params[:id])
     if @todo.update_attributes(params.require(:todo).permit(:title, :body))
       flash[:notice] = "Todo was updated."
       redirect_to @todo
     else
       flash[:error] = "There was an error saving the todo. Please try again."
       render :edit
     end
   end


end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update, :destroy]

  # GET /users/:id.:format
  def show
  end

  def index
     if @user = current_user
     @todos = @user.todos
    else
      flash[:error] = "Not signed in"
      redirect_to root_url
    end
  end

  # GET /users/:id/edit
  def edit
    
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        @user.skip_reconfirmation!
        sign_in(@user, :bypass => true)
        redirect_to @user, notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      accessible = [ :name, :email ] # extend with your own params
      accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
      params.require(:user).permit(accessible)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Doit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= "container">
    <ul class= "nav nav-tabs">
  <ul>
         <li><%= link_to "Doit", root_path %></li>
          <li><%= link_to "About", about_path %></li>

          <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

   </ul>

   <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>

</body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for todos</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @todo do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter todo title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter todo body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/todos/index.html.erb
<h1>All Todos</h1>
<% @todos.each do |todo| %>
   <p><%= link_to todo.title, todo %></p>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= link_to todo.title, todo %>
       </h4>
     </div>
   </div>
<% end %>

app/views/todos/new.html.erb
<h1>Todos#new</h1>
<p>Find me in app/views/todos/new.html.erb</p>

app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>

<%= link_to "Edit", edit_todo_path(@todo), class: 'btn btn-success' %>

<p><%= @todo.body %></p>

app/views/users/finish_signup.html.erb
 <div id="add-email" class="container">
  <h1>Add Email</h1>
  <%= form_for(current_user, :as => 'user', :url => finish_signup_path(current_user), :html => { role: 'form'}) do |f| %>
    <% if @show_errors && current_user.errors.any? %>
      <div id="error_explanation">
        <% current_user.errors.full_messages.each do |msg| %>
          <%= msg %><br>
        <% end %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :email %>
      <div class="controls">
        <%= f.text_field :email, :autofocus => true, :value => '', class: 'form-control input-lg', placeholder: 'Example: email@me.com' %>
        <p class="help-block">Please confirm your email address. No spam.</p>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="col-md-10">
<span class="h1"><%=@user.name%>'s Lists</span>
  <%= link_to "New Todo", new_todo_path(@todo), class: 'btn btn-success center' %>
  <%= link_to "Tweet a reminder", user_omniauth_authorize_path(:twitter), class: 'btn btn-info pull-right'  %>
</div>


<div class="col-md-10">
  <% @todos.each do |todo| %>
    <table class="table table-striped table-hover ">  
        <span class="text-inline h2"><%= link_to "#{todo.title}", todo%></span>
    <% if policy(todo).destroy? %>
      <%= link_to "Delete", [todo], method: :delete, class: 'btn-sm btn-danger pull-right'  %>
    <% end %>
     <tbody>
    <%= render partial: 'items/item', collection: todo.items %>
    </tbody>
    </table>
  <% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Doit</h1>
  <p>Doit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
  <body> 
    <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '540990679365446',
      xfbml      : true,
      version    : 'v2.1'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </body>
</script>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Todo will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Todo will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Todo will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>